symlink config.log to RUN_DIR iff configure_mfix fails

diff --git a/configure_mfix b/configure_mfix
--- a/configure_mfix
+++ b/configure_mfix
@@ -10,6 +10,9 @@ for target in mfix postmfix libmfix.a Makefile; do
     [ -d ${target} ] && exit -1
 done
 
+# config.log is always in BUILD_DIR, but only want it in RUN_DIR if configure fails
+rm -f config.log
+
 # Set some of the folder paths.
 RUN_DIR=$(pwd)
 MFIX_HOME=$(cd $(dirname $0); pwd)
@@ -29,7 +32,15 @@ else
     BUILD_DIR=${MFIX_HOME}/build/${args_dir_name}
     mkdir -p ${BUILD_DIR}
     cd ${BUILD_DIR}
-    ${MFIX_HOME}/configure "${args[@]}" || exit $?
+    set +e
+    ${MFIX_HOME}/configure "${args[@]}"
+    exit_code=$?
+    set -e
+    if [[ $exit_code != 0 ]]; then
+	cd ${RUN_DIR}
+	ln -sf ${BUILD_DIR}/config.log
+	exit $exit_code
+    fi
     MAKEFILE=${RUN_DIR}/Makefile
     MAKEFILE_USR=${BUILD_DIR}/build-aux/Makefile.usr
     if [ -f ${MAKEFILE_USR} ]; then
